#!/usr/bin/env python3

import os

import r12

def main():
    # Check for admin privileges.
    if os.getuid() != 0:
        print('Sorry, the R12 Shell must be run with admin privileges.')
        print('Try running with \'sudo\'.')
        return 1

    # Open the interactive shell.
    shell = r12.ArmShell(r12.Arm())
    shell.cmdloop()


if __name__ == '__main__':
    main()
